### ISSUE TITLE
Projekt i implementacja planszy

### ISSUE THREAD

**Issue by michal-kapala** [purpleturtll/pt-monopoly#1]
Rzeczy, które powinniśmy uwzględnić w **projektowaniu**, jak i **logice gry**:
 1. Pola - zasady, jakie, ile, projekt rozmieszczenia
 2. Design środka planszy - sloty na karty (do wzięcia i zużyte), tło
 3. Inne elementy gry - pionki, kostka, dobór i odkładanie karty, animacje

**Comment by purpleturtll** [comment]
Jeśli chodzi o design planszy to możemy wzorować się na tym:
![image](https://user-images.githubusercontent.com/23462560/112205798-7a5c4000-8c15-11eb-9e17-fc2c2c4dfb77.png)
Myślałem też nad zrobieniem bardziej izometrycznej planszy. Może, coś w stylu into the breach:
![image](https://user-images.githubusercontent.com/23462560/112205900-9e1f8600-8c15-11eb-8758-8aefd5b9479e.png)

**Comment by purpleturtll** [comment]
Nie musimy się też ściśle trzymać zasad klasycznego monopoly. Były różne edycje z terminalem płatniczym lub jednorękim bandytą, więc możemy pójść w kierunku połączenia monopoly z jakimś mechnizmem hazardowym.
